volumes:
  db-data:

services:
  app:
    build:
      context: .
      dockerfile: docker/local/php/Dockerfile
    container_name: app
    ports:
      - 8765:8765
    volumes:
      - ./app:/src
      # https://windows.php.net/download#php-8.4
      - ./docker/local/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
  db:
    build:
      dockerfile: docker/local/mysql/Dockerfile
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./logs/db:/var/log/mysql
      - db-data:/var/lib/mysql
