name: CI

on:
  push:
    branches: ["main", "develop"]
    paths:
      - "app/**"
  pull_request:
    branches: ["main", "develop"]
    paths:
      - "app/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  coding-standard:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, intl
          coverage: none
          tools: cs2pr, phpstan:2.1.22

      - name: Composer install
        uses: ramsey/composer-install@v3
        with:
          working-directory: ./app

      - name: Run PHP CodeSniffer
        run: vendor/bin/phpcs --report=checkstyle src/ | cs2pr

      - name: Run phpstan
        if: always()
        run: phpstan
        env:
          SECURITY_SALT: f76f1c8475585c46c6acd3ddcb8f5e0f15de524637bb4080a08c4afe7cfc9144
